apiVersion: apps/v1
kind: Deployment
metadata:
  name: preview-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: preview-app
  template:
    metadata:
      labels:
        app: preview-app
    spec:
      containers:
      - name: app-container
        # Jenkins will automatically replace 'IMAGE_TAG' with the actual ECR path
        image: IMAGE_TAG 
        ports:
        - containerPort: 3000 # Change this to your app's port (e.g., 8080 or 5000)
---
apiVersion: v1
kind: Service
metadata:
  name: preview-service
spec:
  type: LoadBalancer
  selector:
    app: preview-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000